package uk.ac.sanger.scgcf.jira.lims.enums

/**
 * Enumerated list for the name of transitions.
 * 
 * Created by ke4 on 25/01/2017.
 */
enum TransitionName {

    SS2_REVERT_TO_WITH_CUSTOMER("REVERT_TO_WITH_CUSTOMER"),
    SS2_REVERT_TO_READY_FOR_SS2("REVERT_TO_READY_FOR_SS2"),
    SS2_REVERT_TO_READY_FOR_SUBMISSION("REVERT_TO_READY_FOR_SUBMISSION"),
    SS2_REVERT_TO_READY_FOR_RECEIVING("REVERT_TO_READY_FOR_RECEIVING"),
    SS2_FAIL_ALL_PLATES_IN_GROUP("FAIL_ALL_PLATES_IN_GROUP"),
    SS2_AWAITING_SS2_FEEDBACK("AWAITING_SS2_FEEDBACK"),
    SS2_START_SUBMISSION("START_SUBMISSION"),
    SS2_START_IMPORT_DECLARATION("START_IMPORT_DECLARATION"),
    SS2_FAIL_IN_SPRI_96("FAIL_IN_SPRI_96"),
    SS2_FAIL_IN_SPRI_384("FAIL_IN_SPRI_384"),
    SS2_RE_RUN_REQUESTED_BY_SPRI("RE-RUN_REQUESTED_BY_SPRI"),
    SS2_COMPLETE_SPRI("COMPLETE_SPRI"),
    SS2_FAIL_IN_QUANT("FAIL_IN_QUANT"),
    SS2_FAIL_IN_LIBRARY_PREP("FAIL_IN_LIBRARY_PREP"),
    SS2_RE_RUN_REQUESTED_BY_QUANT("RE_RUN_REQUESTED_BY_QUANT"),
    SS2_RE_RUN_REQUESTED_BY_LIBRARY_PREP("RE_RUN_REQUESTED_BY_LIBRARY_PREP"),
    DNA_FAIL_IN_SPRI_96("FAIL_IN_SPRI_96"),
    DNA_FAIL_IN_SPRI_384("FAIL_IN_SPRI_384"),
    DNA_RE_RUN_REQUESTED_BY_SPRI("RE-RUN_REQUESTED_BY_SPRI"),
    DNA_COMPLETE_SPRI("COMPLETE_SPRI"),
    DNA_FAIL_IN_QUANT("FAIL_IN_QUANT"),
    DNA_RE_RUN_REQUESTED_BY_QUANT("RE_RUN_REQUESTED_BY_QUANT"),
    DNA_FAIL_IN_LIBRARY_PREP("FAIL_IN_LIBRARY_PREP"),
    DNA_RE_RUN_REQUESTED_BY_LIBRARY_PREP("RE_RUN_REQUESTED_BY_LIBRARY_PREP"),
    CMB_FAIL_IN_SPRI("FAIL_IN_SPRI"),
    CMB_COMPLETE_SPRI("COMPLETE_SPRI"),
    ECH_FAIL_IN_SPRI("FAIL_IN_SPRI"),
    ECH_READY_FOR_QUANTIFICATION("READY_FOR_QUANTIFICATION"),
    ECH_START_QUANTIFICATION_ANALYSIS("START_QUANTIFICATION_ANALYSIS"),
    ECH_READY_FOR_NORMALISATION_AND_LIBRARY_PREP("READY_FOR_NORMALISATION_AND_LIBRARY_PREP"),
    ECH_FAIL_IN_QUANTIFICATION_ANALYSIS("FAIL_IN_QUANTIFICATION_ANALYSIS"),
    ECH_FAIL_AND_REQUEST_QUANT_FEEDBACK("FAIL_AND_REQUEST_QUANT_FEEDBACK"),
    ECH_FAIL_OUTRIGHT_AND_REQUEST_QUANT_FEEDBACK("FAIL_OUTRIGHT_AND_REQUEST_QUANT_FEEDBACK"),
    ECH_LIBRARY_PREP_COMPLETED("LIBRARY_PREP_COMPLETED"),
    ECH_REVERT_TO_READY_FOR_LIBRARY_PREP("REVERT_TO_READY_FOR_LIBRARY_PREP"),
    ECH_FAIL_AND_REQUEST_LIBRARY_PREP_FEEDBACK("FAIL_AND_REQUEST_LIBRARY_PREP_FEEDBACK"),
    ECH_FAIL_IN_LIBRARY_PREP("FAIL_IN_LIBRARY_PREP"),
    ECH_REVERT_TO_READY_FOR_LIBRARY_PREP_AFTER_POOLING("REVERT_TO_READY_FOR_LIBRARY_PREP_AFTER_POOLING"),
    LIB_READY_FOR_LIBRARY_POOLING("READY_FOR_LIBRARY_POOLING"),
    LIB_FAIL_IN_LIBRARY_PREP("FAIL_IN_LIBRARY_PREP"),
    LIB_LIBRARY_POOLING_COMPLETED("LIBRARY_POOLING_COMPLETED"),
    LIB_FAIL_IN_LIBRARY_POOLING("FAIL_IN_LIBRARY_POOLING"),
    LIB_REVERT_TO_READY_FOR_POOLING("REVERT_TO_READY_FOR_POOLING"),
    LPL_START_POOLING("START_POOLING"),
    LPL_READY_FOR_BA_QC("READY_FOR_BA_QC"),
    LPL_FAIL_IN_LIBRARY_POOLING("FAIL_IN_LIBRARY_POOLING"),
    LPL_FAIL_IN_BA_QC("FAIL_IN_BA_QC"),
    LPL_RDY_FOR_PRE_NORMALISATION("RDY_FOR_PRE_NORMALISATION"),
    LPL_COMPLETED_PRE_NORMALISATION("COMPLETED_PRE_NORMALISATION"),
    LPL_COMPLETED_PRE_NORMALISATION_AND_EMPTY("COMPLETED_PRE_NORMALISATION_AND_EMPTY"),
    LPL_FAIL_IN_PRE_NORMALISATION("FAIL_IN_PRE_NORMALISATION"),
    PPL_START_PRE_NORMALISATION("START_PRE_NORMALISATION"),
    PPL_FAIL_IN_PRE_NORMALISATION("FAIL_IN_PRE_NORMALISATION"),
    PPL_READY_FOR_QPCR("READY_FOR_QPCR"),
    PPL_START_QPCR("START_QPCR"),
    PPL_READY_FOR_NORMALISATION("READY_FOR_NORMALISATION"),
    PPL_REVERT_TO_READY_FOR_QPCR("REVERT_TO_READY_FOR_QPCR"),
    PPL_REVERT_TO_READY_FOR_QPCR_FOR_RERUN("REVERT_TO_READY_FOR_QPCR_FOR_RERUN"),
    PPL_FAIL_IN_QPCR("FAIL_IN_QPCR"),
    SPRI_ALL_PLATES_RESOLVED("ALL_PLATES_RESOLVED")

    String transitionName

    public TransitionName(String transitionName) {
        this.transitionName = transitionName
    }

    @Override
    String toString() {
        transitionName
    }
}
